-*- after-save-hook: org-babel-tangle; -*-

#+TITLE: Dotfiles
#+PROPERTY: header-args :shebang #!/usr/bin/env bash

* Included

** common
   These are for every machine I use regularly, remote or local.

  - [[https://clojure.org/][clojure]]
  - [[https://git-scm.com/][git]]
  - [[http://ipython.org/][ipython]]
  - [[http://jupyter.org/][jupyter]]
  - [[https://www.r-project.org/][R]]
  - [[http://ranger.nongnu.org/][ranger]]
  - [[https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html][readline]]
  - [[http://www.scala-lang.org/][scala]]
  - [[https://tmux.github.io/][tmux]] (plugins via [[https://github.com/tmux-plugins/tpm][tpm]])
  - [[http://www.vim.org/][vim]] (plugins via [[https://github.com/junegunn/vim-plug][vim-plug]])
  - [[http://zsh.sourceforge.net/][zsh]] (plugins via [[https://github.com/b4b4r07/zplug][zplug]])
  - [[https://www.postgresql.org/][{p,v}sql]]

** local
   These are for a primary non-remote computer.

  - [[http://beets.io/][beets]]
  - [[https://github.com/1995eaton/chromium-vim][cVim]]
  - [[https://www.gnu.org/software/emacs/][Emacs]]
  - [[https://gnupg.org/][gnupg]]
  - [[https://mpv.io/][mpv]]
  - [[http://www.offlineimap.org/][offlineimap]]
  - [[http://surfraw.alioth.debian.org/][surfraw]]

** Linux
   These are for a primary, non-remote Linux computer.

  - [[http://i3wm.org/][i3]]
  - [[https://github.com/jaagr/polybar][polybar]]
  - [[https://www.gtk.org/][gtk]]
  - [[https://davedavenport.github.io/rofi/][rofi]]
  - [[http://jonls.dk/redshift/][redshift]]
  - [[https://github.com/lanoxx/tilda][tilda]]
  - [[https://www.x.org/wiki/][xorg]]

** OSX
   These are for a primary, non-remote OSX computer.

   - [[http://www.hammerspoon.org/][hammerspoon]]
   - [[http://www.launchd.info/][Launchd]]

* Setup

  Clone this repo:

  #+BEGIN_SRC sh :tangle no
  git clone git://github.com/justmytwospence/dotfiles.git $HOME/dotfiles
  #+END_SRC

  The following setup is [[http://orgmode.org/manual/Extracting-source-code.html#Extracting-source-code][tangled]] into executable scripts that use [[https://www.gnu.org/software/stow/][GNU stow]] to
  symlink the dotfiles and perform additional setup as necessary, one for each
  ~$layer~:

  #+BEGIN_SRC sh :tangle no
  $HOME/dotfiles/$layer/bin/bootstrap-$layer
  #+END_SRC

** common
   :PROPERTIES:
   :header-args+: :tangle common/bin/bootstrap-common
   :END:

  #+BEGIN_SRC sh
  stow common --dir $HOME/dotfiles --no-folding
  #+END_SRC

  Set the default shell to zsh:

  #+BEGIN_SRC sh
  chsh -s /usr/local/bin/zsh
  #+END_SRC

  Install zsh plugins:

  #+BEGIN_SRC sh
  zplug install
  #+END_SRC

  Install Vim plugins:

  #+BEGIN_SRC sh
  vim +PlugUpgrade +PlugUpdate +quitall
  #+END_SRC

  Install tmux plugins.

  #+BEGIN_SRC sh
  $HOME/.tmux/plugins/tpm/scripts/install_plugins.sh
  #+END_SRC

** local
   :PROPERTIES:
   :header-args+: :tangle local/bin/bootstrap-local
   :END:

   #+BEGIN_SRC sh
   stow local --dir $HOME/dotfiles --no-folding
   #+END_SRC

** Linux
   :PROPERTIES:
   :header-args+: :tangle linux/bin/bootstrap-linux
   :END:

   #+BEGIN_SRC sh
   stow linux --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Install required packages.

   #+BEGIN_SRC sh
   sudo apt-get install \
   alsa-base \
       android-tools-adb \
       android-tools-fastboot \
       aptitude \
       arc-theme \
       aspell \
       audacity \
       baobab \
       bash \
       breeze-cursor-theme \
       build-essential \
       caca-utils \
       calibre \
       compton \
       emacs \
       firefox \
       fonts-font-awesome \
       fonts-hack-ttf \
       fonts-powerline \
       gawk \
       gimp \
       git \
       gnupg2 \
       gnuplot \
       gparted \
       hsetroot \
       hugo \
       i3-wm \
       i3blocks \
       imagemagick \
       jq \
       kdeconnect \
       less \
       make \
       messengerfordesktop \
       mlocate \
       mpd \
       mpv \
       mu4e \
       npm \
       offlineimap \
       pandoc \
       pinentry-curses \
       pinentry-gtk2 \
       playonlinux \
       postgis \
       postgresql \
       pulseaudio \
       python3 \
       qgis \
       r-base \
       ranger \
       redshift-gtk \
       rofi \
       rsync \
       ruby \
       sed \
       sendmail \
       silversearcher-ag \
       surfraw \
       systemd \
       thunar \
       thunar-dropbox-plugin \
       tilda \
       tmux \
       transmission-gtk \
       trash-cli \
       udiskie \
       vifm \
       vim-gtk3 \
       wget \
       wicd \
       wine-stable \
       xcape \
       xclip \
       xdotool \
       xmacro \
       xournal \
       youtube-dl \
       zsh
   #+END_SRC

   Enable systemd services:
   #+BEGIN_SRC sh
   systemctl --user enable dropbox.service
   systemctl --user enable emacs.service
   systemctl --user enable gpg-agent.service
   systemctl --user enable jupyter.service
   systemctl --user enable offlineimap.service
   systemctl --user enable redshift.service
   #+END_SRC

   Set default browser to Firefox.

   #+BEGIN_SRC sh
   update-alternatives --set x-www-browser $(which firefox)
   xdg-settings set default-web-browser firefox.desktop
   #+END_SRC

** OSX
   :PROPERTIES:
   :header-args+: :tangle osx/bin/bootstrap-osx
   :END:

    #+BEGIN_SRC sh
    stow osx --dir $HOME/dotfiles --no-folding
    #+END_SRC
