-*- after-save-hook: org-babel-tangle; -*-

#+TITLE: Dotfiles
#+PROPERTY: header-args :shebang #!/usr/bin/env bash

* Included

** Linux
   These are for a primary, non-remote Linux computer.

   - dconf
   - [[https://www.gtk.org/][gtk]]
   - [[https://freedesktop.org/wiki/Software/systemd/][systemd]]
   - [[https://github.com/lanoxx/tilda][tilda]]

** OSX
   These are for a primary, non-remote OSX computer.

   - [[http://www.hammerspoon.org/][hammerspoon]]
   - [[http://www.launchd.info/][Launchd]]

** local
   These are for a primary non-remote computer.

   - [[http://beets.io/][beets]]
   - [[https://github.com/1995eaton/chromium-vim][cVim]]
   - [[https://www.gnu.org/software/emacs/][Emacs]]
   - [[https://gnupg.org/][gnupg]]
   - [[https://mpv.io/][mpv]]
   - [[http://www.offlineimap.org/][offlineimap]]
   - [[http://surfraw.alioth.debian.org/][surfraw]]

** common
   These are for every machine I use regularly, remote or local.

   - [[https://clojure.org/][clojure]]
   - [[https://git-scm.com/][git]]
   - [[http://ipython.org/][ipython]]
   - [[http://jupyter.org/][jupyter]]
   - [[https://www.r-project.org/][R]]
   - [[http://ranger.nongnu.org/][ranger]]
   - [[https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html][readline]]
   - [[http://www.scala-lang.org/][scala]]
   - [[https://tmux.github.io/][tmux]] (plugins via [[https://github.com/tmux-plugins/tpm][tpm]])
   - [[http://www.vim.org/][vim]] (plugins via [[https://github.com/junegunn/vim-plug][vim-plug]])
   - [[http://zsh.sourceforge.net/][zsh]] (plugins via [[https://github.com/b4b4r07/zplug][zplug]])
   - [[https://www.postgresql.org/][{p,v}sql]]

* Setup

  Clone this repo and initialize submodules:

  #+BEGIN_SRC sh :tangle no
  git clone git://github.com/justmytwospence/dotfiles.git $HOME/dotfiles
  #+END_SRC

  Generate SSH key:

  #+BEGIN_SRC sh :tangle no
  ssh-keygen -t rsa -b 4096 -C "github@spencerboucher.com"
  #+END_SRC

  Add the SSH key to ssh-agent:

  #+BEGIN_SRC sh :tangle no
  ssh-add $HOME/.ssh/id_rsa
  #+END_SRC

  Now, [[https://github.com/settings/keys][add the public key to GitHub]]:

  Initialize submodules:

  #+BEGIN_SRC sh :tangle no
  (cd $HOME/dotfiles && git submodule init && git submodule update)
  #+END_SRC

  The following setup is [[http://orgmode.org/manual/Extracting-source-code.html#Extracting-source-code][tangled]] into executable scripts that use [[https://www.gnu.org/software/stow/][GNU stow]] to
  symlink the dotfiles and perform additional setup as necessary, one for each
  ~$layer~:

  #+BEGIN_SRC sh :tangle no
  $HOME/dotfiles/$layer/bin/bootstrap-$layer
  #+END_SRC

** Linux
   :PROPERTIES:
   :header-args+: :tangle linux/bin/bootstrap-linux
   :END:

   Restore repositories:

   #+BEGIN_SRC sh
   cp -r $HOME/dotfiles/linux/.config/apt/sources.list* /etc/apt/
   #+END_SRC

   Install packages:

   #+BEGIN_SRC sh
   xargs -a $HOME/dotfiles/linux/.config/apt/packages.txt sudo apt install
   #+END_SRC

   #+BEGIN_SRC sh
   stow linux --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Restore Gnome settings with dconf:

   #+BEGIN_SRC sh
   dconf load / < $HOME/linux/.config/dconf/settings.dconf
   #+END_SRC

   Install yaru (communitheme):

   #+BEGIN_SRC sh
   sudo snap install communitheme
   #+END_SRC

   Restart and select `communitheme` from the dropdown when logging in (/not/ Wayland).

   Install Emacs 26 from source:

   #+BEGIN_SRC sh
   mkdir $HOME/src
   git clone https://git.savannah.gnu.org/git/emacs.git $HOME/src/emacs
   (cd $HOME/dotfiles && git checkout emacs-26.1)
   (cd $HOME/dotfiles && .autogen.sh && ./configure && sudo make && sudo make install)
   #+END_SRC

   Enable systemd services:

   #+BEGIN_SRC sh
   systemctl --user enable emacs.service
   systemctl --user enable jupyter.service
   systemctl --user enable pgweb.service
   #+END_SRC

   Set default browser to Firefox:

   #+BEGIN_SRC sh
   sudo update-alternatives --set x-www-browser $(which firefox)
   xdg-settings set default-web-browser firefox.desktop
   #+END_SRC

** OSX
   :PROPERTIES:
   :header-args+: :tangle osx/bin/bootstrap-osx
   :END:

   Install Homebrew:

   #+BEGIN_SRC sh
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   #+END_SRC

   Install GNU stow:

   #+BEGIN_SRC sh
   brew install stow
   stow osx --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Install Homebrew packages:

   #+BEGIN_SRC sh
   brew bundle --global
   #+END_SRC

** common
   :PROPERTIES:
   :header-args+: :tangle common/bin/bootstrap-common
   :END:

   #+BEGIN_SRC sh
   stow common --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Set the default shell to zsh:

   #+BEGIN_SRC sh
   grep -qF `which zsh` /etc/shells || sudo echo `which zsh` >> /etc/shells
   chsh -s `which zsh`
   #+END_SRC

   Restart.

   Set base16 shell theme:

   #+BEGIN_SRC sh
   base16_tomorrow-night
   #+END_SRC

   Install zsh plugins:

   #+BEGIN_SRC sh
   zplug install
   #+END_SRC

   Install Vim plugins:

   #+BEGIN_SRC sh
   vim +PlugUpgrade +PlugUpdate +quitall
   #+END_SRC

   Install tmux plugins:

   #+BEGIN_SRC sh
   $HOME/.tmux/plugins/tpm/scripts/install_plugins.sh
   #+END_SRC

** local
   :PROPERTIES:
   :header-args+: :tangle local/bin/bootstrap-local
   :END:

   #+BEGIN_SRC sh
   stow local --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Install Jupyter:

   #+BEGIN_SRC sh
   pip3 install jupyter jupyter_contrib_nbextensions
   jupyter contrib nbextension install --user
   #+END_SRC

   Add eterm to terminfo database:

   #+BEGIN_SRC sh
   mkdir $HOME/.terminfo
   cp -r /usr/local/share/emacs/*/etc/e $HOME/.terminfo
   #+END_SRC
