-*- after-save-hook: org-babel-tangle; -*-

#+TITLE: Dotfiles
#+PROPERTY: header-args :shebang #!/usr/bin/env bash

* Included

** common
   These are for every machine I use regularly, remote or local.

   - [[https://clojure.org/][clojure]]
   - [[https://git-scm.com/][git]]
   - [[http://ipython.org/][ipython]]
   - [[http://jupyter.org/][jupyter]]
   - [[https://www.r-project.org/][R]]
   - [[http://ranger.nongnu.org/][ranger]]
   - [[https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html][readline]]
   - [[http://www.scala-lang.org/][scala]]
   - [[https://tmux.github.io/][tmux]] (plugins via [[https://github.com/tmux-plugins/tpm][tpm]])
   - [[http://www.vim.org/][vim]] (plugins via [[https://github.com/junegunn/vim-plug][vim-plug]])
   - [[http://zsh.sourceforge.net/][zsh]] (plugins via [[https://github.com/b4b4r07/zplug][zplug]])
   - [[https://www.postgresql.org/][{p,v}sql]]

** local
   These are for a primary non-remote computer.

   - [[http://beets.io/][beets]]
   - [[https://github.com/1995eaton/chromium-vim][cVim]]
   - [[https://www.gnu.org/software/emacs/][Emacs]]
   - [[https://gnupg.org/][gnupg]]
   - [[https://mpv.io/][mpv]]
   - [[http://www.offlineimap.org/][offlineimap]]
   - [[http://surfraw.alioth.debian.org/][surfraw]]

** Linux
   These are for a primary, non-remote Linux computer.

   - [[https://www.gtk.org/][gtk]]
   - [[https://freedesktop.org/wiki/Software/systemd/][systemd]]
   - [[https://github.com/lanoxx/tilda][tilda]]

** OSX
   These are for a primary, non-remote OSX computer.

   - [[http://www.hammerspoon.org/][hammerspoon]]
   - [[http://www.launchd.info/][Launchd]]

* Setup

  Clone this repo and initialize submodules:

  #+BEGIN_SRC sh :tangle no
  git clone git://github.com/justmytwospence/dotfiles.git $HOME/dotfiles
  (cd $HOME/dotfiles && git submodule init && git submodule update)
  #+END_SRC

  The following setup is [[http://orgmode.org/manual/Extracting-source-code.html#Extracting-source-code][tangled]] into executable scripts that use [[https://www.gnu.org/software/stow/][GNU stow]] to
  symlink the dotfiles and perform additional setup as necessary, one for each
  ~$layer~:

  #+BEGIN_SRC sh :tangle no
  $HOME/dotfiles/$layer/bin/bootstrap-$layer
  #+END_SRC

** common
   :PROPERTIES:
   :header-args+: :tangle common/bin/bootstrap-common
   :END:

  #+BEGIN_SRC sh
  stow common --dir $HOME/dotfiles --no-folding
  #+END_SRC

  Set the default shell to zsh:

  #+BEGIN_SRC sh
  grep -qF `which zsh` /etc/shells || sudo echo `which zsh` >> /etc/shells
  chsh -s `which zsh`
  #+END_SRC

  Install zsh plugins:

  #+BEGIN_SRC sh
  zplug install
  #+END_SRC

  Install Vim plugins:

  #+BEGIN_SRC sh
  vim +PlugUpgrade +PlugUpdate +quitall
  #+END_SRC

  Install tmux plugins:

  #+BEGIN_SRC sh
  $HOME/.tmux/plugins/tpm/scripts/install_plugins.sh
  #+END_SRC

** local
   :PROPERTIES:
   :header-args+: :tangle local/bin/bootstrap-local
   :END:

   #+BEGIN_SRC sh
   stow local --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Add eterm to terminfo database:

   #+BEGIN_SRC sh
   mkdir $HOME/.terminfo
   cp -r /usr/local/share/emacs/*/etc/e $HOME/.terminfo
   #+END_SRC

** Linux
   :PROPERTIES:
   :header-args+: :tangle linux/bin/bootstrap-linux
   :END:

   #+BEGIN_SRC sh
   stow linux --dir $HOME/dotfiles --no-folding
   #+END_SRC

   Enable systemd services:

   #+BEGIN_SRC sh
   systemctl --user enable emacs.service
   systemctl --user enable jupyter.service
   systemctl --user enable mailpile.service
   systemctl --user enable offlineimap.service
   systemctl --user enable pgweb.service
   #+END_SRC

   Set default browser to Firefox:

   #+BEGIN_SRC sh
   update-alternatives --set x-www-browser $(which firefox)
   xdg-settings set default-web-browser firefox.desktop
   #+END_SRC

   Load GNOME configuration:

   #+BEGIN_SRC
   dconf load $HOME/.config/dconf/user.d/custom.conf
   #+END_SRC

** OSX
   :PROPERTIES:
   :header-args+: :tangle osx/bin/bootstrap-osx
   :END:

    #+BEGIN_SRC sh
    stow osx --dir $HOME/dotfiles --no-folding
    #+END_SRC

   Install Homebrew and Homebrew packages:

   #+BEGIN_SRC sh
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   brew bundle --global
   #+END_SRC
